### ISSUE TITLE
Could you please share fmri_net_sim for fmri netsim dataloading 

### ISSUE THREAD

**Issue by SaqibMamoon** [ElleZWQ/JRNGC#1]
Dear @ElleZWQ 

Thank you sharing code online, could you please share the "fmri_net_sim.py" to load the fmri data?

I also have another question, can this code be able to run without groundtruth?

**Comment by ElleZWQ** [comment]
Thank you for your reminder. I have uploaded the file.
Of course, you can run this code without ground truth by deleting or 
Comment the related ground truth part.

Our appendix also talks about this.
